# NetBox Echo服务器 - Perf测试专用配置
application:
  type: echo

network:
  ip: 127.0.0.1
  port: 8888
  io_type: epoll

threading:
  worker_threads: 4
  thread_pool_type: double_lock

logging:
  level: error  # 减少日志输出以提高性能
  async: true

performance:
  max_connections: 10000
  buffer_size: 8192

echo:
  heartbeat_enabled: false  # 关闭心跳提高性能
  protocol: SimpleHeader

protocol:
  default: SimpleHeader
  timeout: 60
