# NetBox EchoRedis 配置文件
# 基于EchoServer架构的Redis实现

application:
  type: echo_redis    # 使用EchoRedis应用

network:
  ip: 192.168.88.135  # 监听IP地址
  port: 6379          # Redis默认端口
  io_type: epoll      # IO多路复用类型

threading:
  worker_threads: 4   # 工作线程数

# 日志配置
logging:
  level: info         # 日志级别
  async: true         # 异步日志

# 性能配置
performance:
  max_connections: 100      # 最大连接数
  buffer_size: 4096         # 缓冲区大小
