# NetBox Redis服务配置文件

# 应用配置
application:
  type: redis_app          # Redis应用类型
  version: 1.0             # 应用版本

# 网络配置
network:
  ip: 0.0.0.0             # 监听所有网络接口
  port: 6379              # Redis服务端口
  io_type: epoll          # IO多路复用类型

# 线程配置
threading:
  worker_threads: 4       # 工作线程数量

# 日志配置
logging:
  level: info             # 日志级别
  file: /app/logs/redis-server.log  # Redis服务日志文件
  async: true             # 异步日志

# 性能配置
performance:
  max_connections: 5000   # 最大连接数
  buffer_size: 4096       # 缓冲区大小
  heartbeat_interval: 30  # 心跳间隔

# Redis服务特定配置
mini_redis:
  max_memory: 50MB        # 最大内存使用
  save_interval: 300      # 持久化间隔
  enable_aof: true        # 启用AOF日志 