# NetBox Echo 服务器配置文件
# 场景：回显服务器，支持心跳保活

# 应用配置 (兼容现有解析逻辑)
application:
  type: echo              # 使用Echo应用

# 网络配置
network:
  ip: 0.0.0.0      # 监听IP地址
  port: 8888              # Echo端口
  io_type: epoll          # IO多路复用类型 (epoll/select/poll)

# 线程配置
threading:
  worker_threads: 4       # 工作线程数
  thread_pool_type: double_lock  # 线程池类型

# 日志配置
logging:
  level: info             # 日志级别 (debug/info/warn/error)
  async: true             # 异步日志

# 性能配置
performance:
  max_connections: 1000   # 最大连接数
  buffer_size: 4096       # 缓冲区大小

# Echo特定配置
echo:
  # 特性: 心跳保活, 4字节协议头, 回显功能
  heartbeat_enabled: true # Echo场景启用心跳
  protocol: SimpleHeader  # 使用简单头部协议

# 协议配置
protocol:
  default: SimpleHeader   # 默认协议
  timeout: 30            # 连接超时时间
