# NetBox Mini Redis 配置文件
application:
  type: mini_redis    # 使用Mini Redis应用

network:
  ip: 192.168.88.135       # 监听IP地址
  port: 6379          # Redis默认端口
  io_type: epoll      # IO多路复用类型

threading:
  worker_threads: 8   # 工作线程数

# Mini Redis 特定配置
mini_redis:
  max_memory: 100MB         # 最大内存使用
  save_interval: 300        # 自动保存间隔（秒）
  enable_persistence: true  # 是否启用持久化
  data_file: redis_data.txt # 数据文件路径

# 日志配置
logging:
  level: info         # 日志级别
  async: true         # 异步日志

# 性能配置
performance:
  max_connections: 1000     # 最大连接数
  buffer_size: 4096         # 缓冲区大小
