# NetBox Direct Redis 配置文件
# 直接Redis实现，无协议转换开销，性能更高

application:
  type: direct_redis     # 使用直接Redis实现

network:
  ip: 192.168.88.135     # 监听IP地址
  port: 6381             # Redis端口 (避免冲突)
  io_type: epoll         # IO多路复用类型 (epoll/select/poll)

threading:
  worker_threads: 4      # 工作线程数
  thread_pool_type: double_lock  # 线程池类型

# 日志配置
logging:
  level: info            # 日志级别 (debug/info/warn/error)
  async: true            # 异步日志

# 性能配置
performance:
  max_connections: 1000  # 最大连接数
  buffer_size: 4096      # 缓冲区大小
  
# Redis特定配置
redis:
  max_memory: 100MB      # 最大内存使用
  command_timeout: 30    # 命令超时时间
