# NetBox 插件化框架配置文件
# 支持通过修改此文件来切换不同的应用类型

# 应用配置
application:
  type: redis_app          # 应用类型: echo, sanguosha, redis_app
  version: 1.0        # 应用版本

# 网络配置
network:
  ip: 192.168.88.135       # 监听IP地址
  port: 6379          # 监听端口
  io_type: epoll      # IO多路复用类型: select, poll, epoll

# 线程配置
threading:
  worker_threads: 10  # 工作线程数量

# 日志配置
logging:
  level: info         # 日志级别: debug, info, warn, error
  file: server.log    # 日志文件路径
  async: true         # 是否使用异步日志

# 性能配置
performance:
  max_connections: 10000    # 最大连接数
  buffer_size: 4096         # 缓冲区大小
  heartbeat_interval: 30    # 心跳间隔（秒）

# 应用特定配置
echo:
  message_prefix: "Echo: "  # 回显消息前缀

# 未来的三国杀配置
sanguosha:
  max_players_per_room: 8   # 每个房间最大玩家数
  room_timeout: 1800        # 房间超时时间（秒）
  enable_ai: true           # 是否启用AI玩家

# 未来的Mini Redis配置
mini_redis:
  max_memory: 100MB         # 最大内存使用
  save_interval: 300        # 持久化间隔（秒）
  enable_aof: true          # 是否启用AOF日志
